import '../../styles/globals.scss'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Header from './header'

const inter = Inter({ subsets: [ 'latin' ] })

export const metadata: Metadata = {
  title: 'airfi-nl | Ops-Visibility',
  description: 'Generated by AirFi',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg`}>
        <Header />
        {children}
      </body>
    </html>
  )
}
